// hooks
export { useClickOutside } from "./web/hooks/use-click-outside";
export { useDidUpdate } from "./web/hooks/use-did-update";
export { useDisclosure } from "./web/hooks/use-disclosure";
export { useFullscreen } from "./web/hooks/use-fullscreen";
export { useMeasureScrollbar, applyStateEffect, attachBodyProperty, detachBodyProperty, attributeState } from "./web/hooks/use-measure-scrollbar";
export { useHotkeys, getHotkeyHandler, getHotkeyMatcher, parseHotkey } from "./web/hooks/use-hotkeys";
export { useHover } from "./web/hooks/use-hover";
export { useIntersection } from "./web/hooks/use-intersection";
export { useInterval } from "./web/hooks/use-interval";
export { useLocalStorage } from "./web/hooks/use-local-storage";
export { useMediaQuery } from "./web/hooks/use-media-query";
export { assignRef, createRefs, mergeRefs, useMergedRef } from "./web/hooks/use-merged-ref";
export { clampUseMovePosition, useMove } from "./web/hooks/use-move";
export { useMouse } from "./web/hooks/use-mouse";
export { useOpenState, Selector, DataAlign, DataSide } from "./web/hooks/use-open-state";
export { createSafeContext, Portal, hasSpecificChildren, modifyChildren } from "./web/hooks/open-state-context";
export { DOTS, range, usePagination } from "./web/hooks/use-pagination";
export { getRandomColor, useRandomColors, useStringToHEx } from "./web/hooks/use-random-colors";
export { useReducedMotion } from "./web/hooks/use-reduced-motion";
export { useElementSize, useResizeObserver } from "./web/hooks/use-resize-observer";
export { useScrollIntoView, easeInOutQuad, getRelativePosition, getScrollStart, setScrollParam } from "./web/hooks/use-scroll-into-view";
export { useUncontrolled } from "./web/hooks/use-uncontrolled";
export { useViewportSize } from "./web/hooks/use-viewport-size";
export { useWindowEvent } from "./web/hooks/use-window-event";
export { useWindowScroll } from "./web/hooks/use-window-scroll";
export { useId, useReactId } from "./web/hooks/use-id";
export { useImagePopup } from "./web/hooks/use-image-popup";
export { useIsomorphicEffect } from "./web/hooks/use-isomorphic-effect";
export { getInputOnChange, useInputState } from "./web/hooks/use-input-state";
export { useStateHistory } from "./web/hooks/use-state-history";
export { useValidatedState } from "./web/hooks/use-validated-state";
export { useClipboard } from "./web/hooks/use-clipboard";
export { useDocumentTitle } from "./web/hooks/use-document-title";
export { useDocumentVisibility } from "./web/hooks/use-document-visibility";
export { useEyeDropper, type EyeDropperOpenReturnType } from "./web/hooks/use-eye-dropper";
export { useFetch, type UseFetchOptions } from "./web/hooks/use-fetch";
export { useNetwork } from "./web/hooks/use-network";
export { useOS, type OS } from "./web/hooks/use-os";
export { useDeviceInfo, type DeviceInfo } from "./web/hooks/use-device-info";
export { useTrigger, useRender } from "./web/hooks/use-trigger";
export { useTouch } from "./web/hooks/use-touch";
export { useOrientation } from "./web/hooks/use-orientation";
export { useReload } from "./web/hooks/use-reload";
export { usePWAInstaller } from "./web/hooks/use-pwa-installer";
export { useElementInfo } from "./web/hooks/use-element-info";
export { useGeoLocation, type CoordinateLocations } from "./web/hooks/use-geo-location";

export type { HotkeyItem, Hotkey, HotkeyItemOptions, KeyboardModifiers } from "./web/hooks/use-hotkeys";
export type { InitialInfo, RectElement, RectInfo } from "./web/hooks/use-element-info";
export type { UseMediaQueryOptions } from "./web/hooks/use-media-query";
export type { UseMovePosition } from "./web/hooks/use-move";
export type { OpenStateOptions, ClickOpenOptions, HoverOpenOptions } from "./web/hooks/use-open-state";
export type { PaginationParams } from "./web/hooks/use-pagination";
export type { StateHistory, UseStateHistoryHandlers } from "./web/hooks/use-state-history";
export { useDialog, useFocusReturn, useLockScroll, useTransition } from "./web/hooks/use-dialog";
export type { TransitionOverride, TransitionStatus } from "./web/hooks/use-dialog";
